# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logger.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'logger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clogger.proto\x12\x05proto\"\xe5\x01\n\nLogRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x10\n\x08severity\x18\x05 \x01(\x05\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x12\x31\n\x08metadata\x18\x07 \x03(\x0b\x32\x1f.proto.LogRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"/\n\x0bLogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2D\n\rLoggerService\x12\x33\n\x08LogEvent\x12\x11.proto.LogRequest\x1a\x12.proto.LogResponse\"\x00\x42\x07Z\x05/logsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\005/logs'
  _globals['_LOGREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_LOGREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_LOGREQUEST']._serialized_start=24
  _globals['_LOGREQUEST']._serialized_end=253
  _globals['_LOGREQUEST_METADATAENTRY']._serialized_start=206
  _globals['_LOGREQUEST_METADATAENTRY']._serialized_end=253
  _globals['_LOGRESPONSE']._serialized_start=255
  _globals['_LOGRESPONSE']._serialized_end=302
  _globals['_LOGGERSERVICE']._serialized_start=304
  _globals['_LOGGERSERVICE']._serialized_end=372
# @@protoc_insertion_point(module_scope)
