server:
  port: 8081

spring:
  application:
    name: authentication-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:users}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET:defaultSecretKeyThatShouldBeChanged12345678901234567890123456789012}
    expiration: 86400 # 24 hours in seconds

grpc:
  client:
    logger-service:
      address: ${LOGGER_SERVICE_URL:logger-service:50001}
      negotiationType: plaintext

logging:
  level:
    com.fourcolour.auth: INFO
    org.springframework.security: DEBUG

# Spring Boot Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  health:
    defaults:
      enabled: true
