server:
  port: 8080
  tomcat:
    max-http-form-post-size: 100MB
    max-swallow-size: 100MB
  max-http-header-size: 64KB

spring:
  application:
    name: api-gateway-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

services:
  coloring:
    url: ${COLORING_SERVICE_URL:http://localhost:8082}
  authentication:
    url: ${AUTHENTICATION_SERVICE_URL:http://localhost:8081}
  map-storage:
    url: ${MAP_STORAGE_SERVICE_URL:http://localhost:8083}

grpc:
  client:
    logger-service:
      address: ${LOGGER_SERVICE_URL:static://localhost:50001}
      negotiationType: plaintext

logging:
  level:
    com.fourcolour.gateway: INFO
    org.springframework.web: DEBUG
