server:
  port: 8081

spring:
  application:
    name: authentication-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:users}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET:defaultSecretKeyThatShouldBeChanged123456789}
    expiration: 86400 # 24 hours in seconds

grpc:
  client:
    logger-service:
      address: ${LOGGER_SERVICE_URL:static://localhost:50001}
      negotiationType: plaintext

logging:
  level:
    com.fourcolour.auth: INFO
    org.springframework.security: DEBUG
