server:
  port: 8084

spring:
  application:
    name: logger-service

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://admin:password@localhost:27017/?authSource=admin}
      database: ${MONGO_DB:logs}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    consumer:
      group-id: logger-service-group
      auto-offset-reset: earliest
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    admin:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

grpc:
  server:
    port: 50001

logging:
  level:
    com.fourcolour.logger: INFO
    org.springframework.kafka: DEBUG
    io.grpc: INFO
