server:
  port: 8083

spring:
  application:
    name: map-storage-service

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://admin:password@mongo:27017/?authSource=admin}
      database: ${MONGO_DB:mapstore}

grpc:
  client:
    logger-service:
      address: ${LOGGER_SERVICE_URL:logger-service:50001}
      negotiationType: plaintext

# Logging
logging:
  level:
    com.fourcolour.mapstorage: INFO

# Spring Boot Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    defaults:
      enabled: true
